-- HailForge AI - Supabase Schema
-- Project: Hail Forge AI App
-- Project ID: pnplxodtpkasiwguugbj

-- Enable Row Level Security
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- ============================================
-- JOBS TABLE
-- ============================================

CREATE TABLE IF NOT EXISTS jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    vin VARCHAR(17) UNIQUE,
    customer_name VARCHAR(255),
    customer_phone VARCHAR(50),
    vehicle VARCHAR(255),
    location VARCHAR(255),
    notes TEXT,
    status VARCHAR(50) DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_jobs_user_id ON jobs(user_id);
CREATE INDEX IF NOT EXISTS idx_jobs_status ON jobs(status);
CREATE INDEX IF NOT EXISTS idx_jobs_vin ON jobs(vin);

-- Update timestamp on row changes
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_jobs_updated_at BEFORE UPDATE ON jobs
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- PROFILES TABLE
-- ============================================

CREATE TABLE IF NOT EXISTS profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name VARCHAR(255),
    role VARCHAR(50) DEFAULT 'technician', -- technician, shop_owner, adjuster
    email VARCHAR(255),
    shop_name VARCHAR(255),
    phone VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_profiles_user_id ON profiles(id);

-- ============================================
-- ROW LEVEL SECURITY POLICIES
-- ============================================

-- Jobs: Users can only see their own jobs
CREATE POLICY "Users can view own jobs"
    ON jobs FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own jobs"
    ON jobs FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own jobs"
    ON jobs FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own jobs"
    ON jobs FOR DELETE
    USING (auth.uid() = user_id);

-- Profiles: Users can only view/update their own profile
CREATE POLICY "Users can view own profile"
    ON profiles FOR SELECT
    USING (auth.uid() = id);

CREATE POLICY "Users can update own profile"
    ON profiles FOR UPDATE
    USING (auth.uid() = id);

-- ============================================
-- AUTH POLICY FOR PROFILE INSERT
-- ============================================

-- Allow users to insert their own profile during signup
CREATE POLICY "Users can insert own profile"
    ON profiles FOR INSERT
    WITH CHECK (auth.uid() = id);

-- ============================================
-- ENABLE EMAIL AUTHENTICATION
-- ============================================

-- This is typically done in Supabase dashboard
-- Go to Authentication → Providers → Email
-- Enable email authentication
-- Configure email templates if needed

-- ============================================
-- DATABASE FUNCTIONS (Optional Enhancements)
-- ============================================

-- Function to get job statistics for a user
CREATE OR REPLACE FUNCTION get_user_stats(user_id UUID)
RETURNS TABLE (
    total_jobs INT,
    pending_jobs INT,
    completed_jobs INT,
    total_value NUMERIC DEFAULT 0
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        COUNT(*) as total_jobs,
        COUNT(*) FILTER (WHERE status = 'pending') as pending_jobs,
        COUNT(*) FILTER (WHERE status = 'completed') as completed_jobs,
        COALESCE(SUM(CASE WHEN status = 'completed' THEN 1000 ELSE 0 END), 0) as total_value
    FROM jobs
    WHERE user_id = auth.uid();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================
-- USAGE EXAMPLES
-- ============================================

-- To test: Run these queries in Supabase SQL Editor

-- 1. Create a test user (run in Supabase dashboard)
-- INSERT INTO auth.users (id, email, encrypted_password, email_confirmed_at)
-- VALUES (
--     gen_random_uuid(),
--     'test@hailforgeai.com',
--     crypt('password123', gen_salt('bf')),
--     NOW()
-- );

-- 2. Create their profile
-- INSERT INTO profiles (id, email, full_name, role)
-- VALUES (
--     'test-user-id',
--     'test@hailforgeai.com',
--     'Test User',
--     'technician'
-- );

-- 3. Insert a test job
-- INSERT INTO jobs (user_id, vin, customer_name, vehicle, status)
-- VALUES (
--     'test-user-id',
--     '1HGCM82633A004352',
--     'John Doe',
--     '2023 Honda Civic',
--     'pending'
-- );

-- 4. Query test user's jobs
-- SELECT * FROM jobs WHERE user_id = 'test-user-id';

-- ============================================
-- NOTES
-- ============================================

-- This schema assumes:
-- 1. Authentication is enabled in Supabase
-- 2. Email/password is the authentication method
-- 3. User IDs are UUIDs from auth.users
-- 4. RLS is enabled on all tables

-- For FlutterFlow integration:
-- 1. Map FlutterFlow "Jobs" collection to Supabase `jobs` table
-- 2. Map FlutterFlow "Profiles" collection to Supabase `profiles` table
-- 3. Use user's auth.uid() for foreign key relationships
-- 4. FlutterFlow's Shadow DOM limitation: User must type in forms manually
